export const AGREGAR_ARTICULOS = 'AGREGAR_ARTICULOS';
export const ERROR_FORMULARIO = 'ERROR_FORMULARIO';
export const ELIMINAR_ARTICULO = 'ELIMINAR_ARTICULO';
export const ARTICULO_ACTUAL = 'ARTICULO_ACTUAL';
export const EDITAR_ARTICULO = 'EDITAR_ARTICULO';
export const DESMARCAR_ARTICULO = 'DESMARCAR_ARTICULO';